/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package atm

import io.kotest.core.spec.style.StringSpec

class AppTest: StringSpec( {
    "hello kotest" {
        println("hello")
    }
})
