/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package atm

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class ATMShould: StringSpec( {
    "give me no coins when ask for nothing" {
        val atm = ATM()

        atm.withdraw(0) shouldBe emptyList()
    }

    "give me one coins of one euro when ask for one euro" {
        val atm = ATM()

        atm.withdraw(1) shouldBe listOf(Money.ONE_COIN)
    }

    "give me one coin of two euros when ask for two euros" {
        val atm = ATM()

        atm.withdraw(2) shouldBe listOf(Money.TWO_COIN)
    }
})
